config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  resources :users
  get 'faq/index'
  root to: 'welcome#index', as: 'welcome'
  resources :athletes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/athlete.rb
class Athlete < ApplicationRecord

    validates :name, :description, :image_url, :strength, :speed, :agility, presence: true
    validates :name, uniqueness: true
    validates :strength, :speed, :agility, numericality: { greater_than_or_equal_to: 0.01 }

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  before_action :set_athlete, only: [:show, :edit, :update, :destroy]

  # GET /athletes
  # GET /athletes.json
  def index
    @athletes = Athlete.all
  end

  # GET /athletes/1
  # GET /athletes/1.json
  def show
  end

  # GET /athletes/new
  def new
    @athlete = Athlete.new
  end

  # GET /athletes/1/edit
  def edit
  end

  # POST /athletes
  # POST /athletes.json
  def create
    @athlete = Athlete.new(athlete_params)

    respond_to do |format|
      if @athlete.save
        format.html { redirect_to @athlete, notice: 'Athlete was successfully created.' }
        format.json { render :show, status: :created, location: @athlete }
      else
        format.html { render :new }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /athletes/1
  # PATCH/PUT /athletes/1.json
  def update
    respond_to do |format|
      if @athlete.update(athlete_params)
        format.html { redirect_to @athlete, notice: 'Athlete was successfully updated.' }
        format.json { render :show, status: :ok, location: @athlete }
      else
        format.html { render :edit }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /athletes/1
  # DELETE /athletes/1.json
  def destroy
    @athlete.destroy
    respond_to do |format|
      format.html { redirect_to athletes_url, notice: 'Athlete was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_athlete
      @athlete = Athlete.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def athlete_params
      params.require(:athlete).permit(:name, :description, :image_url, :strength, :speed, :technique, :agility)
    end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    username = User.find_by(username: params[:username])
    if username.try(:authenticate, params[:password])
      session[:username] = username.id
      redirect_to admin_url
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to store_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:username)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<h1>You have successfully logged in</h1>

<p>
  It's <%= Time.now %>.
</p>

app/views/athletes/_form.html.erb
<%= form_with(model: athlete, local: true) do |form| %>
  <% if athlete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(athlete.errors.count, "error") %> in your athlete form. Please see below for errors</h2>

      <ul>
      <% athlete.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 6, cols: 80 %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :strength %>
    <%= form.text_field :strength %>
  </div>

  <div class="field">
    <%= form.label :speed %>
    <%= form.text_field :speed %>
  </div>

  <div class="field">
    <%= form.label :technique %>
    <%= form.text_field :technique %>
  </div>

  <div class="field">
    <%= form.label :agility %>
    <%= form.text_field :agility %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/athletes/edit.html.erb
<h1>Editing Athlete</h1>

<%= render 'form', athlete: @athlete %>

<%= link_to 'Show', @athlete %> |
<%= link_to 'Back', athletes_path %>

app/views/athletes/index.html.erb
<h1>Athlete List</h1>
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<table>
  

  <tbody>
    <% @athletes.each do |athlete| %>
      <%= content_tag :tr, class: cycle('list_line_odd', 'list_line_even') do %>
  <td>
    <%= image_tag(athlete.image_url, class: 'list_image') %>
  </td>
        
        <td><p>Name</p><%= athlete.name %></td>
        <td><p>Strength</p><%= athlete.strength %></td>
        <td><p>Speed</p><%= athlete.speed %></td>
        <td><p>Technique</p><%= athlete.technique %></td>
        <td><p>Agility</p><%= athlete.agility %></td>
        
        <td class='list_actions'>
  <%= link_to 'Athlete Information', athlete %><br/>
  <%= link_to 'Edit Athlete', edit_athlete_path(athlete) %><br/>
  <%= link_to 'Remove Athlete', athlete, method: :delete,
      data: { confirm: 'Are you sure you want to remove this athlete from the team?' } %>
</td>
     <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Click here to add a new athlete to the team', new_athlete_path %>

app/views/athletes/new.html.erb
<h1>Enter the information of your new athlete</h1>

<%= render 'form', athlete: @athlete %>

<%= link_to 'Back to athlete list', athletes_path %>

app/views/athletes/show.html.erb
<h1>Athlete Information</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @athlete.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @athlete.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @athlete.image_url %>
</p>

<p>
  <strong>Strength:</strong>
  <%= @athlete.strength %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @athlete.speed %>
</p>

<p>
  <strong>Technique:</strong>
  <%= @athlete.technique %>
</p>

<p>
  <strong>Agility:</strong>
  <%= @athlete.agility %>
</p>

<%= link_to 'Edit', edit_athlete_path(@athlete) %> |
<%= link_to 'Back', athletes_path %>

app/views/faq/index.html.erb
<h1>Frequently Asked Questions</h1>
<ol>
    <l1>Who are you?</li>
        <p>We are NUI Galway Athletics Club</p>
        <l1>What do you do?</li>
        <p>We so Athletics</p>
        <l1>Where are you based?</li>
        <p>We are based in NUI Galway</p>
        <l1>Do you have a committee</li>
        <p>Yes! Our committee can be found at https://clubs.nuigalway.ie/clubProfile.php?id=Mjk1</p>
        <l1>Do you guys compete</li>
        <p>Yes! We are one of NUI Galways most successful sports teams at competitions</p>
        <l1>Sounds Great! How do I get in contact about joining?</li>
        <p>Just click this link </p>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracking Application</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div id = "navigation">
  <nav>
  <a class="navbar-brand" href="../"><img src="http://www.assistid.eu/adminbackend/resources/nuigalwaylogocolour300-w400.jpg"></a>
    <ul>
      <li><a = href="../athletes">Our Team</a></li>
      <li><a = href="../faq/index">FAQ</a></li>
      <li><a = href="../users/new">Sign Up</a></li>
      
      <li><a = href="../login">Login</a></li>
    </ul>
</nav>
  </div>

  <body>
  <%= content_tag :main, class: controller.controller_name do %>
    <%= yield %>
  <% end %>
</body>
</html>

app/views/users/_form.html.erb
<div class="depot_form">

<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <legend>Enter User Details</legend>

  <div class="field">
    <%= form.label :username, 'Username:' %>
    <%= form.text_field :username, size: 40 %>
  </div>

  <div class="field">
    <%= form.label :password, 'Password:' %>
    <%= form.password_field :password, size: 40 %>
  </div>


  <div class="field">
    <%= form.label :password_confirmation, 'Confirm:' %>
    <%= form.password_field :password_confirmation, size: 40 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  </fieldset>
<% end %>

</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome to this team management application</h1>
<h2>For NUI Galways Athletics Club Team</h2>

<p>NUI Galway Athletics club has a tremendous backround in Track and field and 
cross country competitions. To date it homes first-class international athletes such 
as Paul Hession and Olive Loughnane. Everybody who joins the club is part of the team 
and has a special role in the club whether they are competing or not. The club competes
 in all intervarsity events annually and there are no individuals in these competitions
  as points are scored by all and everybody cheers everybody else on. The driving force
   behind the mens and womens club is the committee. The committee are elected at the AGM 
   annually. The Events page holds the AGM dates, details and committee members. New members
    are encouraged to join the committee each year.</p>

<a href="./athletes"><button type="button">Click to enter application!</button></a>